### PR TITLE
Fix tb2 demo: #20

### PR DESCRIPTION
**Pull request by corot**

### CODE REVIEW

**Review by gerardcanal — CHANGES_REQUESTED** [review]
Hi corot, 
Thanks for the PR. It looks good, but I am not sure about the changes to the rviz configuration. 
As this PR was to remove the wrong namespace, can you remove those changes from the PR and leave only the changes to the bash files?

Thank you

**Comment by bilal9876** [comment]
hello Mr. gerardcanal . it doesnot work , i have changed the three files but also it didnot work. the same error. 
iam using turtlebot3 demos not the turtlebo2 demo . so, should i change the files in turtlebpt3_demo.

**Comment by corot** [comment]
> Hi corot,
> Thanks for the PR. It looks good, but I am not sure about the changes to the rviz configuration.
> As this PR was to remove the wrong namespace, can you remove those changes from the PR and leave only the changes to the bash files?
> 
> Thank you

Dropped

**Comment by corot** [comment]
> hello Mr. gerardcanal . it doesnot work , i have changed the three files but also it didnot work. the same error.
> iam using turtlebot3 demos not the turtlebo2 demo . so, should i change the files in turtlebpt3_demo.

Probably yes. Please try and open another PR if you manage to fix tir.
Sorry, I just tried TB2 demos

**Comment by gerardcanal** [comment]
Perfect, thank you!
Merging and I'll fix the tb3 one.

**Pull request merged**
